### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#117]
scrot uses the [MIT-advertising](https://spdx.org/licenses/MIT-advertising.html) license. It's a license created by the Enlightenment project which is the project that gave us imlib2, imlib2 is also under the same license.
The Fedora project considers it [incompatible with the GPL](https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising) because of its advertising clause.
If you CTRL-F "MIT-advertising" at [spdx.org/licenses](https://spdx.org/licenses/), you will see that the license is not certified Free/Libre by the FSF nor OSI approved. This is in all likelihood simply because nobody got around to doing it.

I think the lack of certification and the advertising clause are a significant annoyance, unenforceable (and why enforce it?), and that many contributors are unlikely to oppose changing to a license that provides the same terms except for removing the advertising clause. 
Here's the advertising clause: `acknowledgment shall be
given in the documentation and software packages that this Software was
used`

We can only change the license of existing code with permission from the original authors, but we can require all new code to follow a new license. We can also ask the original authors to relicense their contributions.

I'd like to suggest requiring a new license for all new contributions called the [ISC license](https://spdx.org/licenses/ISC.html). It's functionally identical to the MIT license, only its wording is more brief.
Here's a reproduction of it, formatted as an 80 columns per line C comment:
```
/* Copyright <YEAR> <OWNER>
 * 
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted, provided that the above 
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH 
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY 
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR 
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
 * PERFORMANCE OF THIS SOFTWARE.
 */
```
Here are some other pages about the license:
- https://en.wikipedia.org/wiki/ISC_license
- https://www.gnu.org/licenses/license-list.html#ISC

If this is accepted, scrot will require this license for all new contributions, I'll relicense what I've contributed to ISC, and we can start asking contributors to do the same with their existing code.

**Comment by eribertomota** [comment]
> scrot uses the [MIT-advertising](https://spdx.org/licenses/MIT-advertising.html) license. It's a license created by the Enlightenment project which is the project that gave us imlib2, imlib2 is also under the same license.
> The Fedora project considers it [incompatible with the GPL](https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising) because of its advertising clause.


Apache2 is also incompatible with GPL-2 and several very good projects are under Apache2 umbrella. My opinion is that it is not relevant because GPL is also a good example of license with restrictions, making it incompatible with some useful licenses.

Regardless what I think, scrot was originally create by Tom Gilbert in 2000, under this license. scrot has existed for 21 years under this license and this fact has never been publicly condemned. Finally, the most important note: scrot has several copyright holders, including Tom Gilbert. To change the licensing, all copyright holders must explicitly to agree with a new license.

> If you CTRL-F "MIT-advertising" at [spdx.org/licenses](https://spdx.org/licenses/), you will see that the license is not certified Free/Libre by the FSF nor OSI approved. This is in all likelihood simply because nobody got around to doing it.
> 
> I think the lack of certification and the advertising clause are a significant annoyance, unenforceable (and why enforce it?), and that many contributors are unlikely to oppose changing to a license that provides the same terms except for removing the advertising clause.
> Here's the advertising clause: `acknowledgment shall be given in the documentation and software packages that this Software was used`
> 
> We can only change the license of existing code with permission from the original authors, but we can require all new code to follow a new license. We can also ask the original authors to relicense their contributions.


Ok, I hadn't read this far. So, you know the license change mechanism. Do you really think that all people (contributors since 2000) will reply a request? If someone don't reply, we can't change anything.

However, if you're willing to get an agreement from each contributor, go ahead. Remember that this agreement must be obtained via email. I suggest opening an issue to make all this official, in case you get all of them agree. It is important to remember that we are dealing with legal aspects and if there is any problem or claim by someone, only your name will be involved in it, should you decide to go ahead.
