### ISSUE TITLE
Can we avoid libbsd?

### ISSUE THREAD

**Issue by targzeta** [resurrecting-open-source-projects/scrot#208]
On my system I don't have the libbsd installed:
```
checking for libbsd-overlay... no
configure: error: BSD functions not found, libbsd is required
```

I have seen that we have the `--without-libbsd` option, but it doesn't seem to work:
`configure: error: BSD functions not found and --without-libbsd was used`

Is it possible avoiding the use of libbsd?

Thank you in advance,
Emanuele

**Comment by guijan** [comment]
It's not. That option is there for feature testing the need for it. Perhaps it should be renamed.

**Comment by N-R-K** [comment]
I recently realized (due to commit https://github.com/resurrecting-open-source-projects/scrot/commit/95efe09e18801b3e28e6708c364a5a7dddbe6fbb) that on glibc systems, libbsd is no longer a dependency in `master` branch (although this ended up happening due to coincidence).

Unfortunately, musl [doesn't provide `sys/queue.h`](https://wiki.musl-libc.org/faq.html). So on musl systems, you'll still need libbsd.

Looking through the issue tracker, I also see that a couple other people were unhappy about libbsd dependency too. But I don't have any plans to remove/rewrite `sys/queue.h` dependency as of now (although I didn't take a close look at what it's used for).

There's also no guarantee that glibc will stay libbsd free either, but if there's no compelling reason to (re)introduce hard dependency on libbsd (on glibc systems), then I'll probably keep it that way.

**Comment by guijan** [comment]
Haiku, Illumos, and dietlibc don't have that header either. Last time I heard, Haiku was introducing an X11 compatibility layer to their original GUI toolkit, so maybe scrot works there these days. Reimplementing a dependency isn't any better than using the dependency, so even if someone removes the rest of the libbsd bits we use by writing alternatives, I'd really be against it. I intend to at minimum support all the currently maintained libre systems with a POSIX C API and any proprietary unices we can get access to, we've made great progress in that direction during the last 2 years (scrot barely built outside of Debian without patching before I arrived), and libbsd's interfaces help with doing so without confining scrot to the ugliest subset of the POSIX APIs that everyone supports.

I'd expand its usage if I found a good place to use it, that's why I wrote as much in the TODO.md. `strsep()` could replace `strtok()`. `strsep()` is easier to use, but I haven't paid attention to the `strtok()` calls in scrot's source to see if they run into `strtok()`'s weirdness.
