### ISSUE TITLE
non-integer delay is not accepted

### ISSUE THREAD

**Issue by a1ea321** [resurrecting-open-source-projects/scrot#213]
`scrot -d 0.5` stopped working. It spits out: `scrot: option --delay: '0.5' is not a number`

I believe this is after I updated scrot through the package manager in Artix.

I `git clone`d and compiled scrot (tag:1.8.1). The problem is there. Then I tried the scrot obtained through `sudo apt install scrot`. That one works.

If you have nothing against restoring this functionality, please do it or say "do it" to me.

**Comment by daltomi** [comment]
Hi @a1ea321 

Yeah, that doesn't look good; it's confusing.
I don't know where I've seen floating point used before but a value like that is just 0.

The improvement we could make is to indicate, via manpage or error message, that `scrot `does not use floating point numbers in any of its options.

- A note for collaborators in general:
Since early versions, eg `scrot v0.8`, a value of `0.5` results in `0`; internally `atoi()` and `sleep()` do not support floating point numbers;  of course, the difference is that `v0.8` quietly allowed this.

**Comment by a1ea321** [comment]
So you're telling me... All this time I've been using `scrot -d 0.5` but the delay did not have any effect x-D Not my first time cargo cult programming.

I added this for a full screen screenshot triggered by dmenu based command launcher. I vaguely remember the 0.5 being necessary for dmenu to get out of the way. (1 second would have been too long of a wait.)

But now, I can't reproduce that issue. Zero delay seems enough time for dmenu. 

Thanks!
