### ISSUE TITLE
image quality issues

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#351]
JPEG uses BT.601 colormatrix and YCbCr colorspace.

Conversion between the RGB of an X server and the YCbCr of JPEG will run into rounding error. To improve image quality, you can do the conversion at a higher bit depth, and then dither the result down to 8bpc (JPEG is always 8bpc). Imlib doesn't do this, and is unlikely to do so because it uses 8bpc internally. And if we ever add support for interfaces other than X11 (the Linux fb, Wayland, etc), then Imlib can't help us either because maybe Imlib can be made to dither a 10bpc or more image it receives from an X server down to its 8bpc internal format as it receives the image, but it can't do that with other user interfaces it doesn't support.

Additionally, computer screens don't use BT.601 colormatrix, and converting color matrices is a very complex problem, I doubt Imlib uses one of the better algorithms for it, and this task also benefits from doing the conversion at a higher bit depth and then dithering down the result to improve image quality.

This isn't only because of JPEG. WEBP is also an 8bpc only format. AVIF maxes out at 12bpc and HDMI supports 16bpc, even a 12bpc format could benefit from dithering down at some point.

We might want to look into replacing Imlib someday to be able to follow the latest in video and to screenshot it well. Possibly, writing our own code to get images from X11/Wayland/Linux fb/Haiku/Windows/etc, libplacebo for colorspace conversion and dithering where beneficial, then ffmpeg for encoding? That more or less means rewriting most of scrot someday.

**Comment by N-R-K** [comment]
> That more or less means rewriting most of scrot someday.

Yes it's pretty much a complete rewrite, since scrot's code base is very much entangled with both X and imlib2.

And it'll also add a bunch of fairly heavyweight library dependency which not all user might benefit from nor want. And you'd also have to keep compatibility with all of scrot's existing features while doing it.

IMO, at that point it's better to just write something new from scratch with those goals in mind if you're really interested in pursuing it.
