### ISSUE TITLE
Select border on screenshot

### ISSUE THREAD

**Issue by 736b** [resurrecting-open-source-projects/scrot#60]
Sometimes when I use `scrot -s` there's the white selection border visible on the screenshot. Sometimes it doesn't happen.
This is something I had way back when I was on Debian and I still have it nowadays on Gentoo.

Screenshot of the issue:
![2020-11-06-190643_401x78_scrot](https://user-images.githubusercontent.com/49469380/98400675-be82e580-2064-11eb-9a7f-417cffd1d6bd.png)

**Comment by danielittlewood0** [comment]
I have seen this many times too, although I can't reproduce it right now. Usually it occurs as the dragging rectangle gets "stuck" - that is, as I'm drawing the rectangle it will leave a shadow behind in some place on the screen.

Sometimes passing over it again with the rectangle will fix it and the shadow will disappear, but sometimes not. It always appears on the final screenshot.

**Comment by daltomi** [comment]
The `--freeze` option can help in this case.

Some time ago I was trying to partially solve this problem:
https://github.com/resurrecting-open-source-projects/scrot/pull/37#issuecomment-622344942

My plan is to support both types of selection since both have their problems, so the user will choose the one that suits him best.

Selection modes: `classic`, `edge`.

`scrot --select --line mode=?,[properties]`

| Properties | mode="classic" | mode="edge" | Values					|
|----------- |----------------|-------------|---------------------------|
| width      | yes            | yes  		| 1..8						|
| color      | yes            | yes  		| "name", #Hexadecimal	    |
| style      | yes            | no   		| solid,dash				|
| opacity    | no             | yes  		| 10-100					|
| --freeze   | yes            | no   		|      					|

Since the `mode` will be `classic` by default, it will not break the current `scrot` behavior.

```bash
classic:
scrot --select 

classic:
scrot --select --line width=2,color=Gold,style=dash

edge:
scrot --select --line mode=edge,width=2,color=Gold,opacity=40
```

[old branch, only edge mode: issue#36-selection](https://github.com/daltomi/scrot/tree/issue%2336-selection)
