### ISSUE TITLE
picom shadow interfering with scrot selection

### ISSUE THREAD

**Issue by AtifChy** [resurrecting-open-source-projects/scrot#72]
![2021-03-20-114559_386x121_scrot](https://user-images.githubusercontent.com/42291930/111860477-fd5d6c00-8971-11eb-84f8-63b60774485c.png)
I need the class name of scrot selection (mode=edge) to exclude it from picom.

**Comment by daltomi** [comment]
Strange that it happens with picom but I have seen this behavior but with xcompmgr.
I tested picom with: 
```bash
backend = "xrender";
backend = "glx";
```
And everything worked fine. 

Can anyone else confirm that the same thing happens to @AtifChy ?

**Comment by AtifChy** [comment]
is dock shadow enabled in your config? 
```wintypes:
{
  dock = { shadow = true; }
};

**Comment by daltomi** [comment]
No, I do not have it and when I add it I see that everything works works well.
And this is because I have the following my configuration: 
```bash
shadow-exclude = [
    "! name~=''",
]
```
Doc:  _The "! name~=''" part excludes shadows on any "Unknown" windows, this prevents a visual glitch with the XFWM alt tab switcher._ 

That's why it works for me. 

Then I am going to do a PR where we can do the following, that I think it is that you indicate in your first message. 
```bash
shadow-exclude = [
    "class_g = 'scrot'",
]
```

Note that, _By convention, the class name of the application is the same as the program name, but with the first letter capitalized... for historical reasons._
I will not continue that convention, since `scrot`, does not use the resource database.
